{
  "requirements": [
    {
      "id": "temperature",
      "capability": "cloudpath.dev/capability/temperature@1",
      "cardinality": "zero-or-one"
    },
    {
      "id": "illuminance",
      "capability": "cloudpath.dev/capability/illuminance@1",
      "cardinality": "zero-or-one"
    },
    {
      "id": "contact",
      "capability": "cloudpath.dev/capability/hall@1",
      "cardinality": "zero-or-one"
    },
    {
      "id": "vibration",
      "capability": "cloudpath.dev/capability/vibration@1",
      "cardinality": "zero-or-one"
    },
    {
      "id": "alert-sound",
      "capability": "cloudpath.dev/capability/buzzer@1",
      "cardinality": "zero-or-one"
    },
    {
      "id": "alert-light",
      "capability": "cloudpath.dev/capability/led@1",
      "cardinality": "zero-or-one"
    }
  ]
}
